[build]
  command = """
    curl -sSL https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.340/quarto-1.3.340-linux-amd64.tar.gz | tar -xz -C /tmp &&
    export PATH=/tmp/quarto-1.3.340/bin:$PATH &&
    quarto render
  """
  publish = "_site"
